version: '3.0'

scanning-settings:
  max-depth: 10
  exclude:
    - .venv
  include-files:
    - path: pyproject.toml
      file-type: requirements.txt
  system:
    targets: []


report:
  dependency-vulnerabilities:
    enabled: true
    auto-ignore-in-report:
      python:
        environment-results: true
        unpinned-requirements: false
      cvss-severity: []
      vulnerabilities:
        71591:
          reason: We do not use `jinja2` with user input strings
          expires: '2025-06-02'
        70612:
          reason: We do not use `jinja2` with user input strings
          expires: '2025-06-02'

fail-scan-with-exit-code:
  dependency-vulnerabilities:
    enabled: true
    fail-on-any-of:
      cvss-severity:
        - medium
        - high
        - critical
      exploitability:
        - medium
        - high
        - critical

security-updates:
  dependency-vulnerabilities:
    auto-security-updates-limit:
      - patch
