# Micromamba environment file
# https://marketplace.visualstudio.com/items?itemName=corker.vscode-micromamba

name: default

channels:
  - conda-forge

dependencies:
  - python
  - conda-forge::ruff
  - conda-forge::pre-commit
  - pip:
    - pytest>=8.2.0
    - pytest-asyncio>=0.23.6
category: dev
