# Micromamba environment file
# https://marketplace.visualstudio.com/items?itemName=corker.vscode-micromamba

name: default

channels:
  - conda-forge

dependencies:
  - python
  - pip:
     - pyyaml>=6.0.1
     - types-PyYAML>=6.0.12
     - pydantic>=2.7.1
     - twine>=5.0.0
     - python-dotenv>=1.0.1
     - types-requests>=2.31.0
     - types-setuptools>=69.5.0
     - typer>=0.12.3
     - httpx>=0.27.0
     - stamina>=24.2.0
     - httpx-sse>=0.4.0
     - -e . --config-settings editable_mode=compat
