name: Push new release of the package to PyPI

on:
  pull_request:
    types: [closed]
    branches:
      - release-*

jobs:
  push_to_pypi:
    name: Upload release to PyPI
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/hirundo
    permissions:
      contents: write  # Used to push tag with release
      pull-requests: read  # Used to create and merge PR with release
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
          cache: 'pip'
      - name: Push tag with release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git pull origin ${{ github.event.pull_request.base.ref }}
          git tag -a ${{ github.event.pull_request.title }} -m "${{ github.event.pull_request.body }}"
          git push origin ${{ github.event.pull_request.title }}
      - name: Install dependencies & build package
        run: |
          python -m pip install --upgrade pip
          python -m venv .venv
          source .venv/bin/activate
          pip install -r dev-requirements.txt
          pip install build twine
          python -m build
      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: ${{ contains(github.event.pull_request.labels, 'test') }}
        with:
          repository-url: https://test.pypi.org/legacy/
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: ${{ contains(github.event.pull_request.labels, 'release') }}
