name: Push package to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  push_to_testpypi:
    name: Upload release to test PyPI
    if: ${{ github.event_name == 'push' && contains(github.ref, 'b') }}
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/hirundo
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
          cache: 'pip'
      - name: Install dependencies on Linux and macOS
        run: |
          python -m pip install --upgrade pip
          python -m venv .venv
          source .venv/bin/activate
          pip install -r dev-requirements.txt
          pip install build twine
      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
  push_to_pypi:
    name: Upload release to PyPI
    if: ${{ github.event_name == 'push' && !contains(github.ref, 'b') }}
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/hirundo
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
          cache: 'pip'
      - name: Install dependencies on Linux and macOS
        run: |
          python -m pip install --upgrade pip
          python -m venv .venv
          source .venv/bin/activate
          pip install -r dev-requirements.txt
          pip install build twine
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
