name: Push package to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  push_to_pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
          cache: 'pip'
      - name: Install dependencies on Linux and macOS
        run: |
          python -m pip install --upgrade pip
          python -m venv .venv
          source .venv/bin/activate
          pip install -r dev-requirements.txt
          pip install build twine
      - name: Public to PyPI
        run: |
          python -m build
          twine check dist/*
          twine upload -r testpypi hirundo dist/*
          twine upload hirundo dist/*
