name: Run all tests with PyTest

on:
  push:
    tags:
      - "v*"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        optimization-test:
          - FULL_TEST
          - RUN_CLASSIFICATION_AWS_OPTIMIZATION
          - RUN_CLASSIFICATION_GCP_OPTIMIZATION
          - RUN_CLASSIFICATION_GCP_SANITY_OPTIMIZATION
          - RUN_AWS_OD_OPTIMIZATION
          - RUN_OD_GIT_OPTIMIZATION
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install dependencies on Linux and macOS
        run: |
          python -m pip install --upgrade pip
          python -m venv .venv
          source .venv/bin/activate
          pip install -r dev-requirements.txt
      - name: Run PyTest
        run: .venv/bin/pytest
        env:
          API_HOST: ${{ secrets.API_HOST }}
          API_KEY: ${{ secrets.API_KEY }}
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          UNIQUE_ID: ${{ github.ref }}-${{ github.run_number }}
          ${{ matrix.optimization-test }}: true          
