name: Vulnerability scan
on:
  pull_request:
    types: [opened, synchronize]
  merge_group:
    types: [checks_requested]
  push:
    branches:
      - "main"
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  vulnerability-scan:
    strategy:
      matrix:
        requirements:
          - requirements/requirements.txt
          - requirements/dev.txt
          - requirements/docs.txt
          - requirements/pandas.txt
          - requirements/polars.txt
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout hirundo-python-sdk
        uses: actions/checkout@v4
      - name: No-op on pull_request
        if: github.event_name == 'pull_request'
        run: echo "Skipping vulnerability scan on PR; marking job success."
      - uses: pypa/gh-action-pip-audit@v1.1.0
        if: github.event_name != 'pull_request'
        with:
          inputs: ${{ matrix.requirements }}
