name: Vulnerability scan
on:
  pull_request:
    types: [opened, synchronize]
  merge_group:
    types: [checks_requested]
  push:
    branches:
      - "main"
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  vulnerability-scan:
    if: github.event_name != 'pull_request'
    strategy:
      matrix:
        requirements:
          - requirements/requirements.txt
          - requirements/dev.txt
          - requirements/docs.txt
          - requirements/pandas.txt
          - requirements/polars.txt
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout hirundo-client
        uses: actions/checkout@v4

      - uses: pypa/gh-action-pip-audit@v1.1.0
        with:
          inputs: ${{ matrix.requirements }}
